language: csharp

matrix:
  include:
    # Ubuntu 14.04
    - os: linux 
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
    # OSX 10.11
    - os: osx 
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003131
      
# Build netcore packages
script:
  - dotnet --info
  - cd src/
  - dotnet restore
  - cd fssrgen
  - dotnet --verbose pack -c Release --output "../../bin/packages"
  - cd ../FSharp.SRGen.Build.Tasks
  - dotnet --verbose pack -c Release --output "../../bin/packages"
  - cd ../dotnet-fssrgen
  - dotnet --verbose pack -c Release --output "../../bin/packages"
