language: csharp

matrix:
  include:
    # Ubuntu 14.04
    - os: linux 
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
    # OSX 10.11
    - os: osx 
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003131
      

script:
  # dotnet info
  - dotnet --info
  # restore
  - cd src/dotnet-fssrgen
  - dotnet restore
