os: Windows Server 2012

environment:
  matrix:
    - USE_DOTNET_CLI_VERSION: 1.0.0.001461

install:
  # download install script from dotnet/cli repo
  - ps: New-Item -Force -ItemType directory -Path ".\scripts\obtain"
  - ps: Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  # install a specific dotnet/cli version in DOTNET_INSTALL_DIR directory
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnet"
  - ps: .\scripts\obtain\install.ps1 -Channel beta -version $env:USE_DOTNET_CLI_VERSION
  # add dotnet to PATH
  - ps: $env:Path = "$pwd\.dotnet\cli\bin;$env:Path"
  # show current dotnet info
  - ps: echo "Using dotnet '$((Get-Command dotnet).Path)'"
  - ps: dotnet --version

build_script:
  - ps: .\scripts\create_packages.ps1

artifacts:
  - path: 'bin\packages\*.nupkg'

test: off 
version: 0.0.1.{build}
